Bug #1088990 - Once hos apn has been rejected in 4G,UE should back to 3G and doing SS service immediately.
[root cause ] DcNetworkManager listen LISTEN_PRECISE_DATA_CONNECTION_STATE,happen error:
RuntimeException: Unable to create service com.spreadtrum.ims.ImsService: java.lang.SecurityException: Neither user 1001 nor current process has android.permission.READ_PRECISE_PHONE_STATE.
[changes ] Add android.permission.READ_PRECISE_PHONE_STATE.
[side effects]nothing
[self test ]:please refer to the issue
[download normally]:yes
[power on/off normally]:yes
[do common repository/branch inspection]:yes
[is there dependence]:no
[confirm dependent commit]:no
[board]:common
[test case]:please refer to the issue
[reviewers ]zhiwei.fu
[change_type ] feature
[tag_product ] common

Change-Id: I96383b87e66f2fafbe111f208620b8715f25eb1b
(cherry picked from commit 2d20526a4da2d6c5d4df591e74908a4807260b6d)